package io.github.nadodev.calcular.emprestimo.domain.exception;

public class ValidacaoException extends RuntimeException {
    public ValidacaoException(String message) {
        super(message);
    }
} 